using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Da単oEnemigo : MonoBehaviour
{


    public float vidaJugador = 100f;
    public float da単oDelEnemigo = 2.0f;
    public LogicaBarraVida logicaBarraVidaJugadorX;
    [SerializeField] private Transform Player;
    [SerializeField] private Transform respawnPoint;
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }


    private void OnTriggerEnter(Collider other)
    {
        if(other.CompareTag("da単oEnemigo"))
        {
            logicaBarraVidaJugadorX.vidaActual -= da単oDelEnemigo;

        }
    }
}
